
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE   
  config:
    import: configserver:http://localhost:8081

# moved below config to congig server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}    # EUREKA_SERVER_ADDRESS it ia a env variable